import Link from "next/link";
import { DatabaseNotice } from "@/components/database-notice";
import { RepairReviewWorkspace } from "@/components/repair-review-workspace";
import { DateRangeFilter, Field, FilterBar, PageHeader } from "@/components/ui";
import { getRepairReview } from "@/lib/data-quality/queries";

export default async function RepairReviewPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const p = await searchParams, result = await getRepairReview(p), d = result.data, href = (page:number) => `?${new URLSearchParams({ ...p, page: String(page) } as Record<string,string>).toString()}`;
  return <><PageHeader title="Repair Proposal Review" description="Explicit, evidence-first triage of proposed effective-value overlays. Raw Scanz observations remain immutable." action={<div className="flex gap-2"><Link href="/data-quality/repairs" className="rounded border border-[#334158] px-4 py-2 text-sm">Approved Repairs</Link><Link href="/data-quality" className="rounded border border-[#334158] px-4 py-2 text-sm">Quality Dashboard</Link></div>} /><DatabaseNotice configured={result.configured} error={result.error} />
    <form><FilterBar><Field label="Exact ticker" name="ticker" defaultValue={p.ticker} placeholder="NVDA" /><DateRangeFilter from={p.from} to={p.to} /><label className="grid gap-1 text-xs muted"><span>Category</span><select name="category" defaultValue={p.category} className="rounded border border-[#334158] bg-[#0c111b] px-3 py-2 text-sm text-white"><option value="">All</option>{d.categories.map((category:any) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><Field label="Field" name="field" defaultValue={p.field} options={["price","change_percent","trades","volume","dollar_volume"]} /><Field label="Finding" name="findingType" defaultValue={p.findingType} options={["possible_missing_decimal","possible_extra_decimal","possible_column_shift","impossible_percentage","ocr_alignment_error"]} /><Field label="Method" name="method" defaultValue={p.method} options={["decimal_restoration","column_realignment","source_line_reparse","manual_review","external_reference"]} /><Field label="Tier" name="tier" defaultValue={p.tier} options={["A","B","C","D"]} /><Field label="Severity" name="severity" defaultValue={p.severity} options={["critical","high","medium","low","info"]} /><Field label="Min confidence" name="minConfidence" type="number" defaultValue={p.minConfidence} /><Field label="Max confidence" name="maxConfidence" type="number" defaultValue={p.maxConfidence} /><label className="grid gap-1 text-xs muted"><span>Status</span><select name="status" defaultValue={p.status ?? "pending"} className="rounded border border-[#334158] bg-[#0c111b] px-3 py-2 text-sm text-white"><option value="pending">pending</option><option value="approved">approved</option><option value="rejected">rejected</option><option value="superseded">superseded</option><option value="all">all</option></select></label><Field label="Conflict" name="conflict" defaultValue={p.conflict} options={["yes","no"]} /><Field label="Source evidence" name="sourceEvidence" defaultValue={p.sourceEvidence} options={["yes","no"]} /><Field label="Sort" name="sort" defaultValue={p.sort} options={["tier","confidence_desc","confidence_asc","severity","ticker","date","newest","oldest"]} /><Field label="Page size" name="pageSize" defaultValue={String(d.pageSize)} options={["25","50","100"]} /><button className="rounded bg-blue-600 px-4 py-2 text-sm">Apply filters</button></FilterBar></form>
    <RepairReviewWorkspace summary={d.summary} proposals={d.proposals} grouped={d.grouped} />
    <div className="mt-4 flex justify-between text-sm"><span>{d.page > 1 && <Link className="text-blue-400" href={href(d.page - 1)}>Previous</Link>}</span><span className="muted">Page {d.page} · {d.count.toLocaleString()} proposals · maximum 100 per request</span><span>{d.page * d.pageSize < d.count && <Link className="text-blue-400" href={href(d.page + 1)}>Next</Link>}</span></div>
  </>;
}
