import{createClient}from"@/lib/supabase/server";
import{getCrossSourceTimeline}from"@/lib/cross-source/queries";
async function safe<T>(fallback:T,run:(db:any)=>Promise<{data:T|null;error:any}>){const db=await createClient();if(!db)return{data:fallback,configured:false,error:null};try{const r=await run(db);return{data:r.data??fallback,configured:true,error:r.error?.message??null}}catch(e){return{data:fallback,configured:true,error:e instanceof Error?e.message:String(e)}}}
export async function getAIResearchPage(sessionId?:string){return safe<any>({workspaces:[],sessions:[],messages:[],savedSearches:[]},async db=>{const[w,s,ss]=await Promise.all([db.from("research_workspaces").select("id,name,description,updated_at").order("updated_at",{ascending:false}).limit(100),db.from("research_sessions").select("id,title,workspace_id,updated_at").order("updated_at",{ascending:false}).limit(30),db.from("saved_searches").select("id,workspace_id,name,natural_language_query,structured_query").order("updated_at",{ascending:false}).limit(100)]),m=sessionId?await db.from("research_messages").select("*").eq("session_id",sessionId).order("created_at").limit(100):{data:[],error:null};return{data:{workspaces:w.data??[],sessions:s.data??[],messages:m.data??[],savedSearches:ss.data??[]},error:w.error??s.error??ss.error??m.error}})}
export const getResearchWorkspaces=()=>safe<any[]>([],db=>db.from("workspace_activity_summary").select("*").order("last_activity_at",{ascending:false}));
export async function getResearchWorkspace(id:string){return safe<any>({workspace:null,searches:[],items:[],history:[],questions:[],checklist:[],briefs:[],views:[]},async db=>{const[w,s,i,h,q,c,b,v]=await Promise.all([db.from("research_workspaces").select("*").eq("id",id).maybeSingle(),db.from("saved_searches").select("*").eq("workspace_id",id).order("updated_at",{ascending:false}).limit(100),db.from("research_workspace_items").select("*,tickers(symbol,company_name)").eq("workspace_id",id).order("updated_at",{ascending:false}).limit(100),db.from("research_history").select("id,prompt,status,returned_record_count,execution_time_ms,created_at,session_id").eq("workspace_id",id).order("created_at",{ascending:false}).limit(50),db.from("research_questions").select("*").eq("workspace_id",id).order("updated_at",{ascending:false}).limit(100),db.from("research_checklist_items").select("*").eq("workspace_id",id).order("created_at").limit(20),db.from("research_brief_snapshots").select("*").eq("workspace_id",id).order("created_at",{ascending:false}).limit(50),db.from("saved_research_views").select("*").eq("workspace_id",id).order("updated_at",{ascending:false}).limit(100)]);return{data:{workspace:w.data,searches:s.data??[],items:i.data??[],history:h.data??[],questions:q.data??[],checklist:c.data??[],briefs:b.data??[],views:v.data??[]},error:w.error??s.error??i.error??h.error??q.error??c.error??b.error??v.error}})}
export async function getResearchHistory(page=1){const p=Math.max(1,page),from=(p-1)*50;return{...await safe<any[]>([],db=>db.from("research_history").select("*,research_workspaces(name)").order("created_at",{ascending:false}).range(from,from+49)),page:p,pageSize:50}}
export const getWorkspaceTickerOptions=()=>safe<any[]>([],db=>db.from("tickers").select("id,symbol,company_name").order("symbol").limit(1000));
export const getWorkspacePicker=()=>safe<any[]>([],db=>db.from("research_workspaces").select("id,name").order("updated_at",{ascending:false}).limit(100));
export async function getResearchWorkspaceTimeline(items:any[],params:Record<string,string|undefined>={}){const tickerIds=[...new Set<string>(items.map((item:any)=>item.ticker_id).filter(Boolean))].slice(0,20),page=Math.max(1,Number(params.timelinePage)||1),dataMode=params.dataMode==="effective"?"effective"as const:"raw"as const;if(!tickerIds.length)return{data:{items:[],page,pageSize:50,total:0,dataMode},configured:true,error:null};return getCrossSourceTimeline({tickerIds,dataMode,sourceDomains:params.timelineSource?[params.timelineSource as any]:undefined,page,pageSize:50})}
