import { analyticsRows } from "@/lib/analytics/queries";import { toCsv } from "@/lib/analytics/csv";
export const runtime="nodejs";const specs:Record<string,{view:string;columns:string[];extra?:Record<string,string>}>=
{"repeat-movers":{view:"research_priority_detail",columns:["symbol","total_appearances","unique_report_days","gainer_appearances","decliner_appearances","most_active_appearances","number_of_categories_seen","first_seen","last_seen","average_gap","median_gap","recurrence_score","mover_intensity_score"]},
"research-queue":{view:"research_queue_analytics",columns:["priority_rank","symbol","research_priority_score","recurrence_score","mover_intensity_score","total_appearances","unique_report_days","repeat_gainer_count","repeat_decliner_count","last_seen","reason_names","research_status"]},
"extreme-moves":{view:"extreme_move_summary",columns:["symbol","report_date","category_name","move_type","change_percent","volume","previous_appearance_date","days_since_previous_appearance","next_appearance_date","days_until_next_appearance"]},
"categories":{view:"category_statistics",columns:["category_name","total_appearances","unique_tickers","average_appearances_per_ticker","most_recurrent_ticker","average_change_percent","median_change_percent","average_volume","coverage_start","coverage_end"]},
"gainers":{view:"research_priority_detail",extra:{mode:"gainers"},columns:["symbol","gainer_appearances","unique_report_days","highest_gain","average_gap","minimum_gap","last_seen","recurrence_score","mover_intensity_score"]},
"decliners":{view:"research_priority_detail",extra:{mode:"decliners"},columns:["symbol","decliner_appearances","unique_report_days","largest_decline","gainer_to_decliner_count","decliner_to_gainer_count","last_seen","recurrence_score"]},
"most-active":{view:"research_priority_detail",extra:{mode:"most_active"},columns:["symbol","most_active_appearances","avg_volume","avg_dollar_volume","most_active_to_gainer_count","last_seen","recurrence_score"]}};
export async function GET(request:Request,{params}:{params:Promise<{kind:string}>}){const {kind}=await params,s=specs[kind];if(!s)return new Response("Unknown export",{status:404});const url=new URL(request.url),p=Object.fromEntries(url.searchParams) as Record<string,string>;Object.assign(p,s.extra??{});let page=1,first=true;const enc=new TextEncoder();const stream=new ReadableStream({async start(controller){try{while(page<=2000){const r=await analyticsRows(s.view,{...p,page:String(page)});if(r.error)throw new Error(r.error);if(first){controller.enqueue(enc.encode(toCsv(r.data,s.columns)));first=false;}else if(r.data.length)controller.enqueue(enc.encode("\r\n"+toCsv(r.data,s.columns).split("\r\n").slice(1).join("\r\n")));if(r.data.length<r.pageSize)break;page++;}controller.close();}catch(e){controller.error(e);}}});return new Response(stream,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="${kind}.csv"`}});}
