import{NextResponse}from"next/server";import{createAdminClient}from"@/lib/supabase/admin";import{getPriceProvider,listPriceProviders}from"@/lib/prices/providers";export const runtime="nodejs";
export async function GET(){return NextResponse.json({providers:listPriceProviders()})}
export async function POST(request:Request){
 const db=createAdminClient();if(!db)return NextResponse.json({message:"Dedicated Supabase service credentials are not configured."},{status:503});
 const form=await request.formData(),symbol=String(form.get("symbol")??"").trim().toUpperCase(),providerKey=String(form.get("provider")??"csv"),source=String(form.get("source")??providerKey).trim().toLowerCase(),file=form.get("file"),provider=getPriceProvider(providerKey);
 if(!/^[A-Z0-9.\-]{1,15}$/.test(symbol))return NextResponse.json({message:"Enter a valid existing ticker symbol."},{status:400});
 if(!/^[a-z0-9._-]{1,40}$/.test(source))return NextResponse.json({message:"Enter a short source identifier such as polygon or yahoo."},{status:400});
 if(!provider)return NextResponse.json({message:"Unknown price import provider."},{status:400});
 if(!(file instanceof File))return NextResponse.json({message:"Choose a historical price CSV file."},{status:400});
 if(file.size>25*1024*1024)return NextResponse.json({message:"Price file exceeds the 25 MB limit."},{status:413});
 const ticker=await(db as any).from("tickers").select("id").eq("symbol",symbol).maybeSingle();if(ticker.error||!ticker.data)return NextResponse.json({message:"Ticker must already exist before importing prices."},{status:404});
 let raw:any[];try{raw=await provider.historicalDownload({symbol,payload:await file.text()})}catch(error){return NextResponse.json({message:error instanceof Error?error.message:"Price file could not be parsed."},{status:400})}
 const run=await(db as any).from("price_import_runs").insert({source,ticker_id:ticker.data.id,status:"running",records_discovered:raw.length}).select("id").single();if(run.error)return NextResponse.json({message:run.error.message},{status:500});
 const existing=await(db as any).from("price_history").select("date").eq("ticker_id",ticker.data.id).eq("source",source),dates=new Set((existing.data??[]).map((x:any)=>x.date));let inserted=0,updated=0,failed=0;const errors:any[]=[],validDates:string[]=[];
 for(const item of raw){try{const r=provider.normalizePriceRecord(item),validation=provider.validateRecord(r);if(!validation.valid){failed++;errors.push({import_run_id:run.data.id,ticker_id:ticker.data.id,date:r.date||null,error_type:"validation",error_message:validation.errors.join(" "),raw_record:item});continue}const result=await(db as any).from("price_history").upsert({ticker_id:ticker.data.id,date:r.date,open_price:r.openPrice,high_price:r.highPrice,low_price:r.lowPrice,close_price:r.closePrice,adjusted_close:r.adjustedClose,volume:r.volume,trades:r.trades,vwap:r.vwap,source},{onConflict:"ticker_id,date,source"});if(result.error)throw result.error;validDates.push(r.date);if(dates.has(r.date))updated++;else{dates.add(r.date);inserted++}}catch(error){failed++;errors.push({import_run_id:run.data.id,ticker_id:ticker.data.id,error_type:"record",error_message:error instanceof Error?error.message:String(error),raw_record:item})}}
 if(errors.length)await(db as any).from("price_import_errors").insert(errors);
 let analyticsError:string|null=null;if(inserted+updated){const rebuilt=await(db as any).rpc("rebuild_cp7_analytics",{p_ticker_id:ticker.data.id});analyticsError=rebuilt.error?.message??null}
 let status=failed?(inserted+updated?"partial":"failed"):"completed";if(raw.length===0)status="failed";if(analyticsError)status="partial";const sorted=validDates.sort(),errorMessage=analyticsError??(raw.length===0?"The file contained no price records.":failed&&!inserted&&!updated?"No valid price records were imported.":null);
 await(db as any).from("price_import_runs").update({start_date:sorted[0]??null,end_date:sorted.at(-1)??null,status,records_inserted:inserted,records_updated:updated,records_failed:failed,error_message:errorMessage,completed_at:new Date().toISOString()}).eq("id",run.data.id);
 return NextResponse.json({runId:run.data.id,status,recordsDiscovered:raw.length,recordsInserted:inserted,recordsUpdated:updated,recordsFailed:failed,message:analyticsError?`Prices were stored, but the derived analytics rebuild failed: ${analyticsError}`:undefined},{status:status==="failed"?422:200});
}
