import { createClient } from "@/lib/supabase/server";export type AnalyticsResult<T>={data:T;configured:boolean;error:string|null;page:number;pageSize:number};
const allowedSort=new Set(["research_priority_score","recurrence_score","mover_intensity_score","total_appearances","unique_report_days","average_gap","minimum_gap","last_seen","change_percent","report_date","category_name","gainer_appearances","decliner_appearances","most_active_appearances","highest_gain","largest_decline","avg_volume","avg_dollar_volume","gainer_to_decliner_count","decliner_to_gainer_count","most_active_to_gainer_count"]);
export async function analyticsRows(view:string,p:Record<string,string|undefined>,defaults={sort:"research_priority_score",ascending:false}){const db=await createClient(),page=Math.max(1,Number(p.page)||1),pageSize=50;if(!db)return{data:[],configured:false,error:null,page,pageSize} as AnalyticsResult<any[]>;let q:any=(db as any).from(view).select("*",{count:"exact"});
 if(p.minAppearances)q=q.gte("total_appearances",Number(p.minAppearances));if(p.minDays)q=q.gte("unique_report_days",Number(p.minDays));if(p.minRecurrence)q=q.gte("recurrence_score",Number(p.minRecurrence));if(p.minIntensity)q=q.gte("mover_intensity_score",Number(p.minIntensity));if(p.minPriority)q=q.gte("research_priority_score",Number(p.minPriority));if(p.exchange)q=q.eq("exchange",p.exchange);if(p.category)q=view==="category_statistics"?q.eq("category_id",p.category):q.contains("category_ids",[p.category]);if(p.reason)q=q.contains("reason_codes",[p.reason]);if(p.from)q=q.gte(view==="extreme_move_summary"?"report_date":view==="category_statistics"?"coverage_end":"last_seen",p.from);if(p.to)q=q.lte(view==="extreme_move_summary"?"report_date":view==="category_statistics"?"coverage_end":"last_seen",p.to);
 if(p.mode==="gainers")q=q.gt("gainer_appearances",0);if(p.mode==="decliners")q=q.gt("decliner_appearances",0);if(p.mode==="most_active")q=q.gt("most_active_appearances",0);
 if(p.subset==="repeat_gainer")q=q.gte("gainer_appearances",2);if(p.subset==="repeat_decliner")q=q.gte("decliner_appearances",2);if(p.subset==="returning")q=q.eq("mover_classification","returning_mover");if(p.subset==="gainer_decliner")q=q.gt("gainer_to_decliner_count",0);if(p.subset==="decliner_gainer")q=q.gt("decliner_to_gainer_count",0);if(p.subset==="active_gainer")q=q.gt("most_active_to_gainer_count",0);if(p.subset==="active_decliner")q=q.gt("most_active_to_decliner_count",0);
 if(p.subset==="repeat_active")q=q.gte("most_active_appearances",2);
 if(p.status)q=q.eq("research_status",p.status);
 if(p.gapBucket){const ranges:Record<string,[number|null,number|null]>={same_next_day:[0,1],"2_5_days":[2,5],"6_10_days":[6,10],"11_30_days":[11,30],"31_90_days":[31,90],"90_plus_days":[91,null]};const range=ranges[p.gapBucket];if(range){if(range[0]!=null)q=q.gte("average_gap",range[0]);if(range[1]!=null)q=q.lte("average_gap",range[1]);}}
 const sort=allowedSort.has(p.sort??"")?p.sort!:defaults.sort;q=q.order(sort,{ascending:p.direction?p.direction==="asc":defaults.ascending}).range((page-1)*pageSize,page*pageSize-1);const {data,error,count}=await q;return{data:data??[],configured:true,error:error?.message??null,page,pageSize,count:count??0};}
export const getCoverage=async()=>{const db=await createClient();if(!db)return{data:null,configured:false,error:null};const {data,error}=await(db as any).from("historical_analytics_coverage").select("*").single();return{data,error:error?.message??null,configured:true};};
export const getReasons=async()=>{const db=await createClient();if(!db)return[];return((await(db as any).from("research_reason_types").select("*").order("display_order")).data??[]);};
export const getAnalyticsCategories=async()=>{const db=await createClient();if(!db)return[];return((await(db as any).from("market_categories").select("id,name").order("display_order")).data??[]);};
export const getCategoryStats=async()=>{const db=await createClient();if(!db)return{data:[],configured:false,error:null};const {data,error}=await(db as any).from("category_statistics").select("*").order("category_name");return{data:data??[],configured:true,error:error?.message??null};};
export const getCategoryTop=async(categoryId:string)=>{const db=await createClient();if(!db)return[];return((await(db as any).from("ticker_category_frequency").select("*").eq("category_id",categoryId).order("appearance_count",{ascending:false}).limit(25)).data??[]);};
export async function getTickerAnalytics(tickerId:string){const db=await createClient();if(!db)return{summary:null,transitions:[],reasons:[]};const [s,t,r]=await Promise.all([(db as any).from("research_priority_detail").select("*").eq("ticker_id",tickerId).maybeSingle(),(db as any).from("ticker_category_transitions").select("*").eq("ticker_id",tickerId).order("to_date",{ascending:false}),(db as any).from("ticker_research_reasons").select("score,research_reason_types(code,name,description)").eq("ticker_id",tickerId)]);return{summary:s.data,transitions:t.data??[],reasons:r.data??[]};}
