import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { processHistoricalDataQualityAudit, startHistoricalDataQualityAudit } from "@/lib/data-quality/audit";
export const runtime = "nodejs";export const maxDuration = 30;
async function rpc(db:any,name:string,args:Record<string,unknown>){const{data,error}=await db.rpc(name,args);if(error)throw new Error(error.message);return data}
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const db = createAdminClient();if (!db) return NextResponse.json({ message: "Dedicated Supabase service credentials are not configured." }, { status: 503 });const { id } = await params;let body: any;try { body = await request.json(); } catch { return NextResponse.json({ message: "A JSON body is required." }, { status: 400 }); }const actor = String(body.reviewedBy ?? "local-admin").trim(), reason = String(body.reason ?? "").trim();if (!actor || !reason) return NextResponse.json({ message: "Reviewer and reason are required." }, { status: 400 });try {
  if (body.action === "approve") { const current = await db.from("market_data_correction_proposals").select("review_tier,status,is_current").eq("id", String(body.proposalId)).maybeSingle();if (current.error || !current.data) throw new Error(current.error?.message ?? "Proposal not found");if (!["A","B"].includes(current.data.review_tier) || current.data.status !== "pending" || !current.data.is_current) throw new Error("Only active Tier A/B proposals may be approved individually. Use coordinated review for Tier C; Tier D is review-only.");return NextResponse.json(await rpc(db,"approve_market_data_proposal", { p_proposal_id: String(body.proposalId), p_reviewed_by: actor, p_reason: reason })); }
  if (body.action === "reject") return NextResponse.json(await rpc(db,"reject_market_data_proposal", { p_proposal_id: String(body.proposalId), p_reviewed_by: actor, p_reason: reason }));
  if (body.action === "ignore") return NextResponse.json(await rpc(db,"ignore_market_data_finding", { p_finding_id: id, p_reviewed_by: actor, p_reason: reason }));
  if (body.action === "edit") return NextResponse.json({ proposalId: await rpc(db,"edit_market_data_proposal", { p_proposal_id: String(body.proposalId), p_value: body.value == null ? null : String(body.value), p_numeric_value: body.numericValue == null ? null : Number(body.numericValue), p_reviewed_by: actor, p_reason: reason }) });
  if (body.action === "revert") return NextResponse.json(await rpc(db,"revert_market_data_repair", { p_appearance_id: String(body.appearanceId), p_field_name: String(body.fieldName), p_reverted_by: actor, p_reason: reason }));
  if (body.action === "rerun") { const finding = await db.from("market_data_quality_findings").select("appearance_id").eq("id", id).maybeSingle();if (finding.error || !finding.data) throw new Error(finding.error?.message ?? "Finding not found");const runId = await startHistoricalDataQualityAudit(db, [finding.data.appearance_id]);return NextResponse.json(await processHistoricalDataQualityAudit(db, runId, 1)); }
  return NextResponse.json({ message: "Unsupported review action." }, { status: 400 });
 } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : String(error) }, { status: 409 }); } }
