import{createClient}from"@/lib/supabase/server";import type{AccountFilters}from"./types";export const ACCOUNT_PAGE_SIZE=50;
async function safe<T>(fallback:T,run:(db:any)=>Promise<{data:T|null;error:any}>){const db=await createClient();if(!db)return{data:fallback,configured:false,error:null};try{const r=await run(db);return{data:r.data??fallback,configured:true,error:r.error?.message??null}}catch(e){return{data:fallback,configured:true,error:e instanceof Error?e.message:String(e)}}}
const pageOf=(p:AccountFilters)=>Math.max(1,Number(p.page)||1),range=(page:number)=>[(page-1)*ACCOUNT_PAGE_SIZE,page*ACCOUNT_PAGE_SIZE-1]as const;
export async function getPromoterLeaderboard(p:AccountFilters={}){const page=pageOf(p);return{...await safe<any[]>([],async db=>{let ids:string[]|undefined;if(p.ticker){const t=await db.from("account_ticker_statistics").select("account_id,tickers!inner(symbol)").eq("tickers.symbol",p.ticker.toUpperCase());if(t.error)return t;const matched=[...new Set<string>((t.data??[]).map((x:any)=>String(x.account_id)))];if(!matched.length)return{data:[],error:null};ids=matched}let q=db.from("account_intelligence_summary").select("*");if(ids)q=q.in("account_id",ids);if(p.platform)q=q.ilike("platform",`%${p.platform}%`);if(p.username)q=q.ilike("username",`%${p.username}%`);if(p.status)q=q.eq("promoter_status",p.status);if(p.from)q=q.gte("last_activity",p.from);if(p.to)q=q.lte("first_activity",`${p.to}T23:59:59Z`);if(p.minMentions)q=q.gte("total_ticker_mentions",Number(p.minMentions));if(p.minEarly)q=q.gte("early_mentions",Number(p.minEarly));if(p.gainer)q=q.gte("gainer_associations",Number(p.gainer));if(p.decliner)q=q.gte("decliner_associations",Number(p.decliner));return q.order(p.sort??"early_mentions",{ascending:p.direction==="asc"}).range(...range(page))}),page,pageSize:ACCOUNT_PAGE_SIZE}}
export const getAccountSummary=(id:string)=>safe<any>(null,db=>db.from("account_intelligence_summary").select("*").eq("account_id",id).maybeSingle());
export const getAccountTickers=(id:string)=>safe<any[]>([],db=>db.from("account_ticker_statistics").select("*,tickers(symbol)").eq("account_id",id).order("total_mentions",{ascending:false}).limit(500));
export async function getAccountMoverObservations(id:string,p:AccountFilters={}){const page=pageOf(p);return{...await safe<any[]>([],async db=>{let q=db.from("account_mover_observation_detail").select("*").eq("account_id",id);if(p.window)q=q.lte("days_before_mover",Number(p.window));if(p.ticker)q=q.eq("symbol",p.ticker.toUpperCase());return q.order("mention_at",{ascending:false}).range(...range(page))}),page,pageSize:ACCOUNT_PAGE_SIZE}}
export async function getPreMoverAccounts(p:AccountFilters={}){const page=pageOf(p);return{...await safe<any[]>([],async db=>{let q=db.from("account_mover_observation_detail").select("*").in("relationship_type",["before_mover","mover_day"]);if(p.ticker)q=q.eq("symbol",p.ticker.toUpperCase());if(p.username)q=q.ilike("username",`%${p.username}%`);if(p.platform)q=q.ilike("platform",`%${p.platform}%`);if(p.category)q=q.eq("mover_category_id",p.category);if(p.from)q=q.gte("mover_date",p.from);if(p.to)q=q.lte("mover_date",p.to);if(p.window)q=q.lte("days_before_mover",Number(p.window));if(p.minMove)q=q.gte("absolute_move_percent",Number(p.minMove));if(p.minVolume)q=q.gte("mover_volume",Number(p.minVolume));return q.order("mover_date",{ascending:false}).range(...range(page))}),page,pageSize:ACCOUNT_PAGE_SIZE}}
export async function getRecurringAccountTickerRelationships(p:AccountFilters={}){const page=pageOf(p);return{...await safe<any[]>([],async db=>{let q=db.from("recurring_account_ticker_relationships").select("*");if(p.username)q=q.ilike("username",`%${p.username}%`);if(p.ticker)q=q.eq("symbol",p.ticker.toUpperCase());if(p.platform)q=q.ilike("platform",`%${p.platform}%`);if(p.minMentions)q=q.gte("total_mentions",Number(p.minMentions));if(p.minEarly)q=q.gte("pre_mover_mentions",Number(p.minEarly));return q.order(p.sort??"total_mentions",{ascending:p.direction==="asc"}).range(...range(page))}),page,pageSize:ACCOUNT_PAGE_SIZE}}
export const getTickerAccounts=(tickerId:string)=>safe<any[]>([],db=>db.from("account_ticker_statistics").select("*,social_accounts(username,promoter_status,social_sources(name))").eq("ticker_id",tickerId).order("pre_mover_mentions",{ascending:false}).limit(100));
export const getTickerEarliestMentions=(tickerId:string)=>safe<any[]>([],db=>db.from("post_tickers").select("social_posts(id,posted_at,title,body,post_url,social_accounts(id,username),social_sources(name),social_communities(name))").eq("ticker_id",tickerId).order("created_at").limit(20));
export const getTickerMoverDates=(tickerId:string)=>safe<any[]>([],db=>db.from("market_mover_appearances").select("report_date").eq("ticker_id",tickerId).order("report_date",{ascending:false}).limit(100));
export async function getMoverAccounts(tickerId:string,moverDate?:string,window=30){return safe<any[]>([],async db=>{let q=db.from("pre_move_account_observations").select("*").eq("ticker_id",tickerId).lte("days_before_mover",window);if(moverDate)q=q.eq("mover_date",moverDate);return q.order("mention_at",{ascending:false}).limit(100)})}
export const getMoverAppearance=(id:string)=>safe<any>(null,db=>db.from("market_mover_appearances").select("*,tickers(symbol,security_type),market_categories(name,category_type)").eq("id",id).maybeSingle());
export async function getMoverAppearanceAccounts(id:string,window=30){return safe<any[]>([],db=>db.from("account_mover_observation_detail").select("*").eq("mover_appearance_id",id).in("relationship_type",["before_mover","mover_day"]).lte("days_before_mover",window).gte("days_before_mover",0).order("mention_at",{ascending:false}))}
export async function getAccountDashboard(){return safe<any>({tracked:0,preMoveAccounts:0,recurring:0,leaders:[]},async db=>{const[tracked,accounts,relationships,leaders]=await Promise.all([db.from("social_accounts").select("id",{head:true,count:"exact"}).eq("promoter_status","tracked"),db.from("account_mover_observations").select("account_id").eq("relationship_type","before_mover"),db.from("recurring_account_ticker_relationships").select("account_id",{head:true,count:"exact"}),db.from("account_intelligence_summary").select("account_id,username,platform,early_mentions,unique_tickers_before_movers,gainer_associations,average_days_before_mover").gt("early_mentions",0).order("early_mentions",{ascending:false}).limit(10)]);return{data:{tracked:tracked.count??0,preMoveAccounts:new Set((accounts.data??[]).map((x:any)=>x.account_id)).size,recurring:relationships.count??0,leaders:leaders.data??[]},error:tracked.error??accounts.error??relationships.error??leaders.error}})}
