import{createHash}from"node:crypto";
import{RedditSocialProvider,type RedditResearchTransport}from"./adapters/reddit";
import{redditConfiguration,socialResearchConfig}from"./config";
import{TickerMentionResolver}from"./extraction";
import{SocialResearchPlanner}from"./research-planner";
import{deriveSocialResearchTags}from"./research-tags";
import type{ProviderRecord,SocialCoverageStatus}from"./types";

type Db=any;type Queue={id:string;ticker_id:string;appearance_id?:string|null;source_id:string;community?:string|null;date_from:string;date_to:string;attempts:number};
const iso=()=>new Date().toISOString();const message=(error:unknown)=>error instanceof Error?error.message:String(error);
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const rawValue=(r:ProviderRecord,key:string)=>(r.rawPayload as any)?.[key];
const availability=(r:ProviderRecord)=>rawValue(r,"availability")==="removed"||rawValue(r,"removed")===true||rawValue(r,"selftext")==="[removed]"||rawValue(r,"body")==="[removed]"?"removed":rawValue(r,"availability")==="deleted"||rawValue(r,"author")==="[deleted]"||rawValue(r,"authorName")==="[deleted]"||rawValue(r,"selftext")==="[deleted]"||rawValue(r,"body")==="[deleted]"?"deleted":"active";
async function call(db:Db,name:string,args:Record<string,unknown>={}){const result=await db.rpc(name,args);if(result.error)throw result.error;return result.data}

async function markSource(db:Db,sourceId:string,status:string,reason:string,adapter?:RedditResearchTransport){const rate=adapter?.getRateLimitState();await db.from("social_sources").update({provider_status:status,provider_status_reason:reason,last_error:status==="healthy"?null:reason,last_attempted_sync_at:iso(),...(rate?{last_rate_limit_used:rate.used,last_rate_limit_remaining:rate.remaining,last_rate_limit_reset_seconds:rate.resetSeconds,last_rate_limit_observed_at:rate.observedAt}:{})}).eq("id",sourceId)}
async function usage(db:Db,outcome:"success"|"failed"|"rate_limited",cacheHit:boolean){await db.rpc("record_social_provider_request",{p_provider:"reddit",p_outcome:outcome,p_cache_hit:cacheHit})}
const defaultLimitations=["Official Reddit search results are not represented as exhaustive historical coverage.","Deleted or removed content may be unavailable.","Only the explicitly recorded communities, queries, dates, pages, and cursors were researched."];
async function saveCoverage(db:Db,q:Queue,counts:{posts:number;comments:number;accounts:Set<string>},status:SocialCoverageStatus,evidence:any[],cursorExhausted:boolean,limitations:string[]=defaultLimitations){let find=db.from("ticker_social_coverage").select("id").eq("ticker_id",q.ticker_id).eq("source_id",q.source_id).eq("date_from",q.date_from).eq("date_to",q.date_to);find=q.community?find.eq("community",q.community):find.is("community",null);const existing=await find.maybeSingle(),value={ticker_id:q.ticker_id,source_id:q.source_id,community:q.community??null,date_from:q.date_from,date_to:q.date_to,last_researched_at:iso(),posts_found:counts.posts,comments_found:counts.comments,accounts_found:counts.accounts.size,coverage_status:status,provider_cursor_exhausted:cursorExhausted,limitations:[...new Set([...defaultLimitations,...limitations])],query_evidence:evidence};return existing.data?.id?db.from("ticker_social_coverage").update(value).eq("id",existing.data.id):db.from("ticker_social_coverage").insert(value)}

async function persistRecord(db:Db,q:Queue,runId:string,record:ProviderRecord,resolver:TickerMentionResolver,tickers:Map<string,string>){const contentHash=hash(["reddit",record.externalId,record.url,record.postedAt,record.title,record.body]),state=availability(record);let accountId:string|null=null;if(record.username){const existing=await db.from("social_accounts").select("first_seen_at,last_seen_at").eq("source_id",q.source_id).eq("username",record.username).maybeSingle(),observed=record.postedAt??iso(),first=existing.data?.first_seen_at&&existing.data.first_seen_at<observed?existing.data.first_seen_at:observed,last=existing.data?.last_seen_at&&existing.data.last_seen_at>observed?existing.data.last_seen_at:observed;const account=await db.from("social_accounts").upsert({source_id:q.source_id,username:record.username,display_name:record.displayName??null,profile_url:record.profileUrl??null,external_account_id:record.username,first_seen_at:first,last_seen_at:last,account_status:"active",last_verified_at:iso(),provider_metadata:{provider:"reddit"}},{onConflict:"source_id,username"}).select("id").single();if(account.error)throw account.error;accountId=account.data.id}
 let communityId:string|null=null;if(record.community){const community=await db.from("social_communities").upsert({source_id:q.source_id,name:record.community,slug:record.community.toLowerCase(),community_type:"subreddit",url:`https://www.reddit.com/r/${record.community}`},{onConflict:"source_id,name"}).select("id").single();if(community.error)throw community.error;communityId=community.data.id}
 let raw=await db.from("social_raw_records").select("id").eq("source_id",q.source_id).eq("content_hash",contentHash).maybeSingle();if(raw.error)throw raw.error;if(!raw.data){raw=await db.from("social_raw_records").insert({source_id:q.source_id,import_run_id:runId,external_id:record.externalId??null,record_type:record.type,source_url:record.url??null,posted_at:record.postedAt??null,raw_text:[record.title,record.body].filter(Boolean).join("\n")||null,raw_payload:state==="active"?record.rawPayload:null,content_hash:contentHash,parse_status:"parsed"}).select("id").single();if(raw.error)throw raw.error}
 if(state!=="active"&&record.externalId)await db.from("social_raw_records").update({raw_text:null,raw_payload:null,source_url:null}).eq("source_id",q.source_id).eq("external_id",record.externalId);
 const prior=await db.from("social_posts").select("id,account_id").eq("source_id",q.source_id).eq("external_post_id",record.externalId).maybeSingle();const post=await db.from("social_posts").upsert({source_id:q.source_id,account_id:accountId,community_id:communityId,external_post_id:record.externalId,submission_external_id:record.rootExternalId??(record.type==="post"?record.externalId:null),external_parent_id:record.externalParentId??null,post_url:state==="active"?record.url??null:null,permalink:state==="active"?record.url??null:null,title:state==="active"?record.title??null:null,body:state==="active"?record.body??null:null,posted_at:record.postedAt??null,source_created_at:record.postedAt??null,edited_at:record.editedAt??null,upvotes:record.upvotes??null,downvotes:record.downvotes??null,score:record.score??null,comments:record.comments??null,upvote_ratio:record.upvoteRatio??null,is_self_post:record.isSelfPost??null,post_type:record.type,raw_payload:state==="active"?record.rawPayload:null,content_hash:contentHash,raw_record_id:raw.data.id,import_run_id:runId,availability_status:state,retrieved_at:iso(),compliance_checked_at:state==="active"?null:iso(),provider_metadata:{provider:"reddit",access_mode:socialResearchConfig.redditProviderMode}},{onConflict:"source_id,external_post_id"}).select("id").single();if(post.error)throw post.error;if(state!=="active"){await db.from("social_content_compliance_log").insert({source_id:q.source_id,post_id:post.data.id,action:"content_tombstoned",reason:`Reddit returned ${state} content during bounded refresh.`,evidence:{external_id:record.externalId,state}});if(prior.data?.account_id&&(rawValue(record,"author")==="[deleted]"||rawValue(record,"authorName")==="[deleted]"||rawValue(record,"availability")==="deleted"))await call(db,"tombstone_reddit_account",{p_account_id:prior.data.account_id,p_reason:"Reddit returned a deleted author during bounded refresh."})}
 const relationPatch:any={};if(record.externalParentId){const parent=await db.from("social_posts").select("id").eq("source_id",q.source_id).eq("external_post_id",record.externalParentId).maybeSingle();if(parent.data)relationPatch.parent_post_id=parent.data.id}if(record.rootExternalId){const root=await db.from("social_posts").select("id").eq("source_id",q.source_id).eq("external_post_id",record.rootExternalId).maybeSingle();if(root.data)relationPatch.root_post_id=root.data.id}if(Object.keys(relationPatch).length)await db.from("social_posts").update(relationPatch).eq("id",post.data.id);
 const text=[record.title,record.body].filter(Boolean).join("\n"),mentions=resolver.resolve(text);let order=1;for(const mention of mentions.resolved){const tickerId=tickers.get(mention.symbol);if(!tickerId)continue;await db.from("post_tickers").upsert({post_id:post.data.id,ticker_id:tickerId,mention_order:order++,mention_text:mention.mentionText,extraction_method:mention.method,confidence_score:mention.confidence,context_excerpt:mention.contextExcerpt,resolver_version:"ticker-mention-v2"},{onConflict:"post_id,ticker_id"})}for(const mention of mentions.unresolved)await db.from("unresolved_ticker_mentions").upsert({post_id:post.data.id,raw_record_id:raw.data.id,symbol_candidate:mention.symbol,mention_text:mention.mentionText,context_excerpt:mention.contextExcerpt,source_id:q.source_id,resolution_status:"pending"},{onConflict:"post_id,symbol_candidate"});for(const tag of deriveSocialResearchTags(text))await db.from("social_post_research_tags").upsert({post_id:post.data.id,tag:tag.tag,confidence:tag.confidence,reason:tag.reason,method_version:tag.methodVersion},{onConflict:"post_id,tag,method_version"});
 return{inserted:!prior.data,post:record.type==="post",comment:record.type==="comment"||record.type==="reply",account:accountId};}

export async function processSocialResearchQueue(db:Db,options:{queueId?:string;limit?:number;adapter?:RedditResearchTransport}={}){const configuration=redditConfiguration();if(!configuration.ready)return{claimed:0,results:[],blocked:true,providerCalls:0,reason:configuration.message};const adapter=options.adapter??new RedditSocialProvider(),claimed=await db.rpc("claim_social_research_queue",{p_limit:Math.max(1,Math.min(options.limit??socialResearchConfig.batchSize,5)),p_queue_id:options.queueId??null});if(claimed.error)throw claimed.error;const results=[];for(const q of(claimed.data??[])as Queue[]){const started=Date.now(),counts={posts:0,comments:0,accounts:new Set<string>()},seenRecords=new Set<string>(),evidence:any[]=[],runCounters={requests:0,cacheHits:0,cacheMisses:0,inserted:0,updated:0,comments:0,mentions:0},run=await db.from("social_import_runs").insert({source_id:q.source_id,import_type:"historical_backfill",status:"running",requested_start_at:q.date_from,requested_end_at:q.date_to,metadata:{queue_id:q.id,phase:"2C",provider:"reddit",access_mode:socialResearchConfig.redditProviderMode}}).select("id").single();adapter.setRequestLifecycle({beforeRequest:async()=>{const reserved=await db.rpc("reserve_social_provider_request",{p_provider:"reddit",p_daily_budget:socialResearchConfig.dailyRequestBudget});if(reserved.error)throw reserved.error;if(!reserved.data)throw Object.assign(new Error("Daily provider request budget reached."),{status:429,retryable:true,budgetExhausted:true,skipProviderRetry:true});runCounters.requests++},afterRequest:outcome=>usage(db,outcome,false)});try{if(run.error)throw run.error;const ticker=await db.from("tickers").select("id,symbol,company_name").eq("id",q.ticker_id).single();if(ticker.error)throw ticker.error;const universe=await db.from("tickers").select("id,symbol,company_name").limit(10_000);if(universe.error)throw universe.error;const tickerIds=new Map<string,string>((universe.data??[]).map((x:any)=>[x.symbol.toUpperCase(),x.id])),resolver=new TickerMentionResolver((universe.data??[]).map((x:any)=>({symbol:x.symbol,companyName:x.company_name}))),planner=new SocialResearchPlanner(),plan=planner.plan({symbol:ticker.data.symbol,companyName:ticker.data.company_name,community:q.community,dateFrom:q.date_from,dateTo:q.date_to,maxQueries:9});let exhausted=true,coverageStatus:SocialCoverageStatus=socialResearchConfig.redditProviderMode==="devvit_bridge"?"provider_limited":"partial";const providerLimitations=new Set<string>();
	  for(const query of plan){
	   let records:ProviderRecord[]=[],after:string|undefined,pages=0,queryExhausted=false;const pagination:Record<string,unknown>[]=[];const cached=await db.from("social_provider_cache").select("response_payload,cursor,status").eq("source_id",q.source_id).eq("cache_key",query.cacheKey).gt("expires_at",iso()).maybeSingle(),cachedPayload=cached.data?.response_payload;
	   if(cached.data){runCounters.cacheHits++;await usage(db,"success",true);records=Array.isArray(cachedPayload?.records)?cachedPayload.records:[];after=cached.data.cursor??undefined;pages=Number(cachedPayload?.pages)||0;queryExhausted=cachedPayload?.providerCursorExhausted===true;if(cachedPayload?.coverageStatus==="provider_limited")coverageStatus="provider_limited";for(const limitation of cachedPayload?.limitations??[])if(typeof limitation==="string")providerLimitations.add(limitation);for(const state of cachedPayload?.pagination??[])pagination.push(state)}
	   else{
	    runCounters.cacheMisses++;let requestUrl=socialResearchConfig.devvitBridgeUrl||"https://oauth.reddit.com";do{try{const page=await adapter.searchTicker({community:query.community,query:query.query,after,limit:100});records.push(...page.records);after=page.nextCursor;requestUrl=page.requestUrl??requestUrl;queryExhausted=Boolean(page.providerCursorExhausted);if(page.coverageStatus==="provider_limited")coverageStatus="provider_limited";for(const limitation of page.limitations??[])providerLimitations.add(limitation);if(page.paginationState)pagination.push(page.paginationState);pages++}catch(error:any){if(error?.budgetExhausted&&pages>0){exhausted=false;break}throw error}}while(after&&pages<socialResearchConfig.maxQueryPages);if(after)queryExhausted=false;exhausted&&=queryExhausted;
	    const thread=records.find(r=>r.type==="post"&&Boolean(r.externalId)&&Number(r.comments??0)>0);if(thread?.externalId)try{const comments=await adapter.fetchComments(thread.externalId,100);records=[...records,...comments.records];if(comments.coverageStatus==="provider_limited")coverageStatus="provider_limited";for(const limitation of comments.limitations??[])providerLimitations.add(limitation);if(comments.paginationState)pagination.push({operation:"get_comments",...comments.paginationState})}catch(error:any){if(error?.budgetExhausted)exhausted=false;else throw error}
	    await db.from("social_provider_cache").upsert({source_id:q.source_id,cache_key:query.cacheKey,request_url:requestUrl,response_payload:{records,pages,providerCursorExhausted:queryExhausted,coverageStatus,limitations:[...providerLimitations],pagination},status:records.length?"success":"empty",cursor:after??null,retrieved_at:iso(),expires_at:new Date(Date.now()+socialResearchConfig.cacheTtlHours*3_600_000).toISOString()},{onConflict:"source_id,cache_key"});
	   }
	   evidence.push({community:query.community,query:query.query,date_from:query.dateFrom,date_to:query.dateTo,records_returned:records.length,cache_hit:Boolean(cached.data),coverage_status:coverageStatus,provider_cursor_exhausted:queryExhausted,pagination_state:pagination});
   for(const record of records){if(record.postedAt&&((q.date_from&&record.postedAt<q.date_from)||(q.date_to&&record.postedAt>q.date_to)))continue;const recordKey=record.externalId??hash([record.type,record.url,record.postedAt,record.title,record.body]);if(seenRecords.has(recordKey))continue;seenRecords.add(recordKey);const saved=await persistRecord(db,q,run.data.id,record,resolver,tickerIds);if(saved.inserted)runCounters.inserted++;else runCounters.updated++;if(saved.post)counts.posts++;if(saved.comment){counts.comments++;runCounters.comments++}if(saved.account)counts.accounts.add(saved.account)}
  }
	  await saveCoverage(db,q,counts,coverageStatus,evidence,exhausted,[...providerLimitations]);
  await call(db,"rebuild_cp6_analytics",{p_ticker_id:q.ticker_id,p_source_id:q.source_id,p_start_at:q.date_from,p_end_at:q.date_to});
  await call(db,"rebuild_phase2c_social_derivatives",{p_ticker_ids:[q.ticker_id]});await call(db,"rebuild_account_intelligence");await call(db,"refresh_social_search_documents",{p_ticker_ids:[q.ticker_id]});
  await call(db,"finish_social_research_queue",{p_queue_id:q.id,p_status:"partial",p_coverage_status:coverageStatus,p_posts:counts.posts,p_comments:counts.comments,p_accounts:counts.accounts.size,p_cursor_state:{queries_completed:evidence.length},p_error:null,p_available_after:null});
	  await db.from("social_import_runs").update({status:"completed",records_discovered:counts.posts+counts.comments,records_inserted:runCounters.inserted,records_updated:runCounters.updated,completed_at:iso(),metadata:{queue_id:q.id,coverage_status:coverageStatus,query_evidence:evidence,access_mode:socialResearchConfig.redditProviderMode,provider_limitations:[...providerLimitations]}}).eq("id",run.data.id);
  await db.from("social_provider_runs").insert({queue_id:q.id,ticker_id:q.ticker_id,source_id:q.source_id,provider:"reddit",status:"partial",requests_made:runCounters.requests,cache_hits:runCounters.cacheHits,cache_misses:runCounters.cacheMisses,posts_inserted:runCounters.inserted,posts_updated:runCounters.updated,comments_inserted:runCounters.comments,accounts_observed:counts.accounts.size,duration_ms:Date.now()-started,rate_limit_used:adapter.getRateLimitState().used,rate_limit_remaining:adapter.getRateLimitState().remaining,rate_limit_reset_seconds:adapter.getRateLimitState().resetSeconds,started_at:new Date(started).toISOString(),completed_at:iso()});
	  await db.from("social_sources").update({provider_status:"healthy",provider_status_reason:`Last bounded ${socialResearchConfig.redditProviderMode==="devvit_bridge"?"Devvit":"legacy OAuth"} research completed with disclosed ${coverageStatus} coverage.`,last_successful_sync_at:iso(),last_error:null}).eq("id",q.source_id);results.push({queueId:q.id,status:"partial",posts:counts.posts,comments:counts.comments,accounts:counts.accounts.size,coverageStatus});
 }catch(error:any){const status=String(error?.status??"");const providerStatus=status==="authorization_required"?"authorization_required":status==="authentication_required"?"unconfigured":error?.status===429?"rate_limited":"degraded",retryable=error?.retryable===true||error?.status===429||error?.status>=500,availableAfter=retryable?new Date(Date.now()+(error?.budgetExhausted?86_400_000:Math.min(3_600_000,30_000*2**Math.min(q.attempts,6)))).toISOString():null,coverageStatus:SocialCoverageStatus=error?.status===429?"rate_limited":retryable?"failed":"not_available";await db.from("social_provider_failures").insert({queue_id:q.id,ticker_id:q.ticker_id,source_id:q.source_id,community:q.community,date_from:q.date_from,date_to:q.date_to,attempt:q.attempts,http_status:Number.isInteger(error?.status)?error.status:null,error_type:status||error?.name||"provider_error",error_message:message(error),retryable,available_after:availableAfter});await saveCoverage(db,q,counts,coverageStatus,[],false);await db.rpc("finish_social_research_queue",{p_queue_id:q.id,p_status:retryable?"deferred":"not_available",p_coverage_status:coverageStatus,p_posts:counts.posts,p_comments:counts.comments,p_accounts:counts.accounts.size,p_cursor_state:null,p_error:message(error),p_available_after:availableAfter});if(run.data?.id)await db.from("social_import_runs").update({status:"failed",completed_at:iso(),error_message:message(error)}).eq("id",run.data.id);await markSource(db,q.source_id,providerStatus,message(error),adapter);results.push({queueId:q.id,status:retryable?"deferred":"not_available",error:message(error)})}}
 return{claimed:(claimed.data??[]).length,results};}
