import{metadataConfig}from"./config";import type{MetadataCacheState,MetadataReason,MetadataSignals,TickerMetadata}from"./types";
type TickerRecord=Record<string,unknown>;
const fields:Record<MetadataReason,(keyof TickerMetadata)[]>={ticker_search:["company_name","exchange"],ticker_page:["company_name","exchange","sector","industry"],ai_search:["sector","industry","market_cap"],watchlist:["company_name","exchange"],alert:["company_name","exchange"],pattern_match:["company_name","exchange","sector","industry"],dashboard:["company_name","exchange"],recent_market_mover:["company_name","exchange","sector","industry"],popular_ticker:["company_name","exchange","sector","industry"],manual:["company_name","exchange","sector","industry","market_cap","shares_outstanding","country","website","security_type","cik","currency"],stale_refresh:["company_name","exchange","sector","industry"],retry:["company_name","exchange","sector","industry"]};
const base:Record<MetadataReason,number>={ai_search:100,ticker_page:95,watchlist:90,alert:90,pattern_match:85,manual:80,dashboard:75,recent_market_mover:70,ticker_search:70,popular_ticker:60,retry:50,stale_refresh:20};
export class MetadataDecisionEngine{
 constructor(private staleDays=metadataConfig.staleDays){}
 determineRequiredFields(reason:MetadataReason,explicit?:readonly (keyof TickerMetadata)[]){return[...new Set(explicit?.length?explicit:fields[reason])]}
 shouldRefreshTicker(ticker:TickerRecord,now=new Date()){const next=typeof ticker.next_metadata_refresh_at==="string"?Date.parse(ticker.next_metadata_refresh_at):NaN;if(Number.isFinite(next))return next<=now.getTime();const updated=typeof ticker.metadata_updated_at==="string"?Date.parse(ticker.metadata_updated_at):NaN;return Number.isFinite(updated)&&updated+this.staleDays*86_400_000<=now.getTime()}
 resolveCacheState(ticker:TickerRecord,required:readonly(keyof TickerMetadata)[],now=new Date()){const missing=required.filter(key=>ticker[key]==null||ticker[key]===""),cooldown=typeof ticker.next_retry_at==="string"&&Date.parse(ticker.next_retry_at)>now.getTime(),active=String(ticker.enrichment_status)==="enriching";let state:MetadataCacheState;if(active)state="refreshing";else if(!missing.length&&this.shouldRefreshTicker(ticker,now))state="stale";else if(!missing.length)state="complete";else if(cooldown&&ticker.last_not_found_at)state="not_found";else if(cooldown)state="failed";else if(ticker.metadata_updated_at)state="partial";else state="pending";return{state,missing,cooldown,usable:missing.length===0}}
 shouldEnrichTicker(ticker:TickerRecord,required:readonly(keyof TickerMetadata)[],force=false){const cache=this.resolveCacheState(ticker,required);return force?!cache.cooldown:cache.missing.length>0&&!cache.cooldown}
 calculatePriority(reason:MetadataReason,signals:MetadataSignals={}){return Math.min(150,base[reason]+(signals.watchlisted?10:0)+(signals.recentMover?8:0)+(signals.activeAlert?8:0)+(signals.patternActivity?5:0)+Math.min(15,Math.floor((signals.popularityScore??0)/10))+Math.min(10,Math.floor((signals.aiSearchCount??0)/5)))}
 async queueTicker(db:any,tickerId:string,reason:MetadataReason,requiredFields:readonly(keyof TickerMetadata)[],priority?:number){const{data,error}=await db.rpc("queue_ticker_metadata",{p_ticker_id:tickerId,p_reason:reason,p_required_fields:requiredFields,p_priority:priority??null,p_available_after:null});if(error)throw new Error(error.message);return String(data)}
}
