import type{NormalizedExchange,SecurityType,TickerMetadata}from"./types";

const aggregators=["finance.yahoo.com","google.com","marketwatch.com","bloomberg.com","reuters.com","sec.gov"];
export function normalizeExchange(value:unknown):NormalizedExchange|null{const x=String(value??"").trim().toUpperCase();if(!x)return null;if(/^NASDAQ\b/.test(x)||["XNAS","XNGS","XNCM","XNMS"].includes(x))return"NASDAQ";if(["NYSE AMERICAN","NYSE AMEX","AMEX","XASE"].includes(x))return"NYSE American";if(["NYSE","NEW YORK STOCK EXCHANGE","XNYS"].includes(x))return"NYSE";if(/^(OTC|OTCQX|OTCQB|PINK|GREY)/.test(x)||["OTCM","OOTC","PINX"].includes(x))return"OTC";if(/^CBOE\b/.test(x)||["BATS","XCBO","BZX","EDGX"].includes(x))return"Cboe";return"Other"}
export function normalizeSecurityType(value:unknown,name=""):SecurityType|null{const x=`${String(value??"")} ${name}`.toLowerCase();if(!x.trim())return null;if(/\b(exchange.?traded fund|etf)\b/.test(x))return"ETF";if(/\b(exchange.?traded note|etn)\b/.test(x))return"ETN";if(/\b(warrant|warrants|wt)\b/.test(x))return"warrant";if(/\b(unit|units)\b/.test(x))return"unit";if(/\b(american depositary|depositary share|adr)\b/.test(x))return"ADR";if(/\b(preferred|preference)\b/.test(x))return"preferred_stock";if(/\b(closed.?end fund|cef)\b/.test(x))return"closed_end_fund";if(/\b(common stock|common shares?|ordinary shares?|equity)\b/.test(x))return"common_stock";return"other"}
export function normalizeAbsoluteNumber(value:unknown,providerMultiplier=1):number|null{if(value==null||value==="")return null;if(typeof value==="number")return Number.isFinite(value)&&value>=0?value*providerMultiplier:null;const text=String(value).trim().replace(/[$,\s]/g,"");const m=text.match(/^(-?\d+(?:\.\d+)?)([KMBT])?$/i);if(!m)return null;const n=Number(m[1]),suffix={K:1e3,M:1e6,B:1e9,T:1e12}[m[2]?.toUpperCase()as"K"|"M"|"B"|"T"]??1,result=n*suffix*providerMultiplier;return Number.isFinite(result)&&result>=0?result:null}
export function normalizeCik(value:unknown):string|null{const digits=String(value??"").replace(/\D/g,"");return digits&&digits.length<=10?digits.padStart(10,"0"):null}
export function normalizeIsin(value:unknown):string|null{const text=String(value??"").trim().toUpperCase();return/^[A-Z]{2}[A-Z0-9]{9}[0-9]$/.test(text)?text:null}
export function normalizeWebsite(value:unknown):string|null{let text=String(value??"").trim();if(!text)return null;if(!/^https?:\/\//i.test(text))text=`https://${text}`;try{const url=new URL(text);if(url.protocol!=="https:")url.protocol="https:";url.hash="";if(aggregators.some(host=>url.hostname===host||url.hostname.endsWith(`.${host}`)))return null;return url.toString().replace(/\/$/,"")}catch{return null}}
export function cleanText(value:unknown,max=300):string|null{const text=String(value??"").replace(/\s+/g," ").trim();return text?text.slice(0,max):null}
export function compactMetadata(value:TickerMetadata):TickerMetadata{return Object.fromEntries(Object.entries(value).filter(([,v])=>v!==null&&v!==undefined&&v!==""))as TickerMetadata}
export function validateMetadata(metadata:TickerMetadata):string[]{const issues:string[]=[];for(const key of["market_cap","float_shares","shares_outstanding"]as const){const v=metadata[key];if(v!=null&&(!Number.isFinite(v)||v<0))issues.push(`${key} must be a non-negative absolute number`)}if(metadata.website&&!normalizeWebsite(metadata.website))issues.push("website must be a canonical HTTPS company URL");if(metadata.cik&&!/^\d{10}$/.test(metadata.cik))issues.push("CIK must contain exactly ten digits");if(metadata.float_shares!=null&&metadata.shares_outstanding!=null&&metadata.float_shares>metadata.shares_outstanding)issues.push("float_shares exceeds shares_outstanding; provider semantics require review");return issues}
