import{MetadataDecisionEngine}from"./decision-engine";import{metadataConfig}from"./config";import{configuredTickerMetadataProviders}from"./providers";import type{MetadataReason,MetadataResolution,TickerMetadata,TickerMetadataProvider}from"./types";
const tickerProjection="id,symbol,company_name,exchange,primary_exchange,sector,industry,market_cap,float_shares,shares_outstanding,country,website,security_type,cik,isin,cusip,currency,active,delisted,enrichment_source,enrichment_status,metadata_version,metadata_updated_at,next_metadata_refresh_at,metadata_refresh_attempts,metadata_priority,metadata_last_requested_at,enrichment_error,last_not_found_at,next_retry_at,failure_reason";
const rpc=async(db:any,name:string,args:Record<string,unknown>)=>{const{data,error}=await db.rpc(name,args);if(error)throw new Error(error.message);return data};
const tomorrow=()=>{const d=new Date();d.setUTCHours(24,0,0,0);return d.toISOString()};
const retryAt=(attempt:number)=>new Date(Date.now()+Math.min(24*60,5*2**Math.max(1,attempt))*60_000).toISOString();
const hasValue=(ticker:Record<string,unknown>,key:keyof TickerMetadata)=>ticker[key]!=null&&ticker[key]!=="";
const relevant=(provider:TickerMetadataProvider,missing:readonly(keyof TickerMetadata)[])=>!provider.supportedFields||missing.some(field=>provider.supportedFields!.includes(field));

export async function processMetadataQueue(db:any,options:{limit?:number;queueId?:string;providers?:TickerMetadataProvider[];signal?:AbortSignal}={}){const providers=options.providers??configuredTickerMetadataProviders(),limit=Math.max(1,Math.min(options.limit??metadataConfig.batchSize,10)),items=await rpc(db,"claim_ticker_metadata_queue",{p_limit:limit,p_queue_id:options.queueId??null})as any[],results:any[]=[];for(const item of items){const result=await processQueueItem(db,item,providers,options.signal);results.push(result)}return{claimed:items.length,processed:results.length,results,providers:providers.map(x=>x.name)}}
async function processQueueItem(db:any,item:any,providers:TickerMetadataProvider[],signal?:AbortSignal){const deferTimeout=async(callsMade=0)=>{const available=new Date(Date.now()+60_000).toISOString(),queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"deferred",p_provider:null,p_error:"Bounded worker time expired; request remains resumable",p_available_after:available});return{queueId:item.id,status:"deferred",reason:"worker_timeout",calls:callsMade,queue}};if(signal?.aborted)return deferTimeout();const{data,error}=await db.from("tickers").select(tickerProjection).eq("id",item.ticker_id).maybeSingle();let ticker=data;if(error||!ticker){await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"failed",p_provider:null,p_error:error?.message??"Ticker no longer exists",p_available_after:null});return{queueId:item.id,status:"failed"}}const required=(Array.isArray(item.required_fields)?item.required_fields:[])as(keyof TickerMetadata)[],reasons=Array.isArray(item.reasons)?item.reasons:[],forcedRefresh=item.reason==="manual"||item.reason==="stale_refresh"||reasons.includes("manual")||reasons.includes("stale_refresh");let missing=forcedRefresh?[...required]:required.filter(key=>!hasValue(ticker,key));if(!missing.length){await rpc(db,"record_metadata_cache_event",{p_provider:ticker.enrichment_source??"cache",p_hit:true,p_avoided:true});const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"completed",p_provider:ticker.enrichment_source??null,p_error:null,p_available_after:null});return{queueId:item.id,status:"completed",cacheHit:true,queue}}
 if(ticker.next_retry_at&&Date.parse(ticker.next_retry_at)>Date.now()){const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"deferred",p_provider:null,p_error:"Ticker retry cooldown is active",p_available_after:ticker.next_retry_at});return{queueId:item.id,status:"deferred",reason:"cooldown",queue}}
 await db.from("tickers").update({enrichment_status:"enriching"}).eq("id",ticker.id);let calls=0,found=false,notFound=0,lastFailure:any=null,usedProvider:string|null=null;
 for(const provider of providers){if(signal?.aborted)return deferTimeout(calls);if(!relevant(provider,missing))continue;const health=await db.from("metadata_provider_health").select("status,rate_limited_until").eq("provider",provider.name).maybeSingle(),h=health.data;if(h?.status==="rate_limited"&&h.rate_limited_until&&Date.parse(h.rate_limited_until)>Date.now())continue;const callsBefore=calls;const response=await provider.lookupTicker(ticker.symbol,{signal,beforeExternalCall:async()=>{const allowed=Boolean(await rpc(db,"reserve_metadata_provider_call",{p_provider:provider.name,p_daily_budget:metadataConfig.dailyBudget}));if(allowed)calls++;return allowed}});usedProvider=provider.name;if(signal?.aborted)return deferTimeout(calls);if(response.errorType==="quota_exhausted"){const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"deferred",p_provider:provider.name,p_error:"Daily metadata API budget exhausted",p_available_after:tomorrow()});return{queueId:item.id,status:"deferred",reason:"quota",calls,queue}}if(response.status==="failed"){lastFailure=response;const limited=response.errorType==="rate_limited";if(calls>callsBefore)await rpc(db,"finish_metadata_provider_call",{p_provider:provider.name,p_outcome:limited?"rate_limited":"failed",p_error:response.errorMessage??null,p_cooldown_seconds:limited?3600:null});continue}if(calls>callsBefore)await rpc(db,"finish_metadata_provider_call",{p_provider:provider.name,p_outcome:"succeeded",p_error:null,p_cooldown_seconds:null});if(response.status==="not_found"){notFound++;continue}found=true;await rpc(db,"apply_ticker_metadata_queue_result",{p_queue_id:item.id,p_provider:provider.name,p_status:response.status,p_metadata:response.metadata,p_error_type:null,p_error_message:null,p_retryable:false,p_stale_days:metadataConfig.staleDays,p_not_found_days:metadataConfig.notFoundCooldownDays,p_max_retries:metadataConfig.maxRetries});const refreshed=await db.from("tickers").select(tickerProjection).eq("id",ticker.id).single();if(refreshed.data)ticker=refreshed.data;missing=required.filter(key=>!hasValue(ticker,key));if(!missing.length)break
 }
 if(found){await rpc(db,"refresh_ticker_research_documents",{p_ticker_ids:[ticker.id]});const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"completed",p_provider:usedProvider,p_error:missing.length?`Provider coverage did not include: ${missing.join(", ")}`:null,p_available_after:null});return{queueId:item.id,status:"completed",calls,missing,queue}}
 if(notFound>0&&!lastFailure){await rpc(db,"apply_ticker_metadata_queue_result",{p_queue_id:item.id,p_provider:usedProvider??"configured_providers",p_status:"not_found",p_metadata:{},p_error_type:"not_found",p_error_message:"No configured provider returned a supported security",p_retryable:false,p_stale_days:metadataConfig.staleDays,p_not_found_days:metadataConfig.notFoundCooldownDays,p_max_retries:metadataConfig.maxRetries});const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"completed",p_provider:usedProvider,p_error:"Not found; retry cooldown applied",p_available_after:null});return{queueId:item.id,status:"not_found",calls,queue}}
 if(!providers.length){const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:"deferred",p_provider:null,p_error:"No metadata provider is configured",p_available_after:tomorrow()});return{queueId:item.id,status:"deferred",reason:"unconfigured",calls,queue}}
 const exhausted=item.attempts>=metadataConfig.maxRetries,available=exhausted?null:retryAt(item.attempts);await rpc(db,"apply_ticker_metadata_queue_result",{p_queue_id:item.id,p_provider:lastFailure?.provider??usedProvider??providers[0].name,p_status:"failed",p_metadata:{},p_error_type:lastFailure?.errorType??"provider_unavailable",p_error_message:lastFailure?.errorMessage??"No configured provider could supply required metadata",p_retryable:!exhausted,p_stale_days:metadataConfig.staleDays,p_not_found_days:metadataConfig.notFoundCooldownDays,p_max_retries:metadataConfig.maxRetries});const queue=await rpc(db,"finish_ticker_metadata_queue",{p_queue_id:item.id,p_status:exhausted?"failed":"deferred",p_provider:lastFailure?.provider??usedProvider,p_error:lastFailure?.errorMessage??"Provider unavailable",p_available_after:available});return{queueId:item.id,status:exhausted?"failed":"deferred",calls,queue}}

export async function resolveMetadataRequest(db:any,options:{tickerId:string;reason:MetadataReason;requiredFields?:readonly(keyof TickerMetadata)[];sync?:boolean;force?:boolean}):Promise<MetadataResolution>{
 const engine=new MetadataDecisionEngine(),first=await db.from("tickers").select(tickerProjection).eq("id",options.tickerId).maybeSingle();
 if(first.error||!first.data)throw new Error(first.error?.message??"Ticker not found");
 let ticker=first.data as Record<string,unknown>;
 const nextRefresh=()=>typeof ticker.next_metadata_refresh_at==="string"?ticker.next_metadata_refresh_at:null;
 if(["ticker_search","ticker_page","ai_search","watchlist","alert","pattern_match"].includes(options.reason))await rpc(db,"track_ticker_popularity",{p_ticker_id:options.tickerId,p_event:options.reason,p_increment:1});
 const required=engine.determineRequiredFields(options.reason,options.requiredFields),cache=engine.resolveCacheState(ticker,required),provider=String(ticker.enrichment_source??"cache");
 if(cache.usable&&!options.force){
  await rpc(db,"record_metadata_cache_event",{p_provider:provider,p_hit:true,p_avoided:true});
  if(cache.state==="stale"){
   const queueId=await engine.queueTicker(db,options.tickerId,"stale_refresh",required);
   await db.from("tickers").update({enrichment_status:"stale"}).eq("id",options.tickerId);
   ticker={...ticker,enrichment_status:"stale"};
   return{ticker,state:"stale",requiredFields:required,missingFields:[],cacheHit:true,queued:true,queueId,providerCallsMade:0,reason:"refresh_queued",nextRefreshAt:nextRefresh(),message:"Stale metadata remains usable and was queued for background refresh."};
  }
  const reason=options.reason==="manual"?"refresh_not_due":"cache_hit";
  return{ticker,state:"complete",requiredFields:required,missingFields:[],cacheHit:true,queued:false,providerCallsMade:0,reason,nextRefreshAt:nextRefresh(),message:"Required metadata served from cache."};
 }
 await rpc(db,"record_metadata_cache_event",{p_provider:provider,p_hit:false,p_avoided:cache.cooldown});
 if(cache.cooldown)return{ticker,state:cache.state,requiredFields:required,missingFields:cache.missing,cacheHit:false,queued:false,providerCallsMade:0,reason:"provider_unavailable",nextRefreshAt:nextRefresh(),message:"Provider retry cooldown is active; cached metadata remains available."};
 const priorityData=await rpc(db,"calculate_ticker_metadata_priority",{p_ticker_id:options.tickerId,p_reason:options.reason}),queueId=await engine.queueTicker(db,options.tickerId,options.reason,required,Number(priorityData));
 let calls=0,queueStatus="pending",queueReason="";
 if(options.sync){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),metadataConfig.syncTimeoutMs);
  try{
   const processed=await processMetadataQueue(db,{limit:1,queueId,signal:controller.signal}),outcome=processed.results[0];
   calls=processed.results.reduce((sum:number,x:any)=>sum+Number(x.calls??0),0);
   queueStatus=String(outcome?.status??"pending");queueReason=String(outcome?.reason??"");
  }finally{clearTimeout(timer)}
  const refreshed=await db.from("tickers").select(tickerProjection).eq("id",options.tickerId).single();if(refreshed.data)ticker=refreshed.data;
 }
 const final=engine.resolveCacheState(ticker,required),stillQueued=!options.sync||["deferred","pending","processing"].includes(queueStatus);
 const reason=queueReason==="quota"?"budget_exhausted":queueReason==="unconfigured"||queueReason==="worker_timeout"||queueReason==="cooldown"||queueStatus==="failed"||queueStatus==="deferred"?"provider_unavailable":queueStatus==="not_found"?"not_found":!options.sync?(options.force?"refresh_queued":"queued"):final.missing.length?"partial":options.force?"refresh_completed":"enriched";
 const message=!final.missing.length?"Required metadata was enriched and cached.":queueStatus==="completed"?"Refresh completed with partial provider coverage; existing cached fields were preserved.":queueStatus==="not_found"?"No configured provider found this security; retry cooldown is active.":"Metadata is queued; available cached fields were returned.";
 return{ticker,state:final.state,requiredFields:required,missingFields:final.missing,cacheHit:false,queued:stillQueued,queueId,providerCallsMade:calls,reason,nextRefreshAt:nextRefresh(),message};
}

export async function preflightAIResearchMetadata(db:any,plan:any){if(plan?.intent!=="metadata_screen")return{requested:0,resolved:0,pending:0};let ids:string[]=[];if(plan.filters?.tickers?.length){const rows=await db.from("tickers").select("id").in("symbol",plan.filters.tickers).limit(5);ids=(rows.data??[]).map((x:any)=>x.id)}else{let q:any=db.from("ticker_statistics").select("ticker_id,tickers!inner(id,exchange)").order("total_appearances",{ascending:false}).limit(5);if(plan.filters?.exchange)q=q.eq("tickers.exchange",plan.filters.exchange);const rows=await q;ids=(rows.data??[]).map((x:any)=>x.ticker_id)}let resolved=0;for(const id of ids){const result=await resolveMetadataRequest(db,{tickerId:id,reason:"ai_search",requiredFields:["sector","industry","market_cap"],sync:true});if(!result.missingFields.length)resolved++}return{requested:ids.length,resolved,pending:ids.length-resolved}}
