"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

export function DataQualityAuditControls({ latestRun }: { latestRun?: any }) {
  const router = useRouter(), [runId, setRunId] = useState<string | null>(latestRun?.status === "pending" || latestRun?.status === "running" ? latestRun.id : null), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [pendingProposals, setPendingProposals] = useState<number | null>(null);
  useEffect(() => { fetch("/api/admin/data-quality/proposals/summary", { cache: "no-store" }).then(response => response.ok ? response.json() : null).then(body => setPendingProposals(body?.pending_proposals ?? null)).catch(() => {}); }, []);
  async function start() { setBusy(true);setMessage("");try { const response = await fetch("/api/admin/data-quality/audits", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }), body = await response.json();if (!response.ok) throw new Error(body.message ?? "Could not start audit");setRunId(body.auditRunId);setMessage(`Audit ${body.auditRunId} is persisted and ready for 250-row batches.`);router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  async function process() { if (!runId) return;setBusy(true);setMessage("");try { const response = await fetch(`/api/admin/data-quality/audits/${runId}/process`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ limit: 250 }) }), body = await response.json();if (!response.ok) throw new Error(body.message ?? "Audit batch failed");const run = body.run ?? {};setMessage(`Processed ${run.processed_rows ?? 0} / ${run.total_rows ?? 0}. Findings: ${run.findings_created ?? 0}. Proposals: ${run.proposals_created ?? 0}.`);if (["completed", "partial", "failed", "cancelled"].includes(run.status)) setRunId(null);router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  return <div className="panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Bounded historical audit</h2><p className="mt-1 text-sm muted">Each request claims at most 250 persisted work items. Interrupted processing resumes from the durable audit run without duplicating findings.</p></div><div className="flex gap-2"><Link href="/data-quality/review" className="rounded bg-blue-600 px-4 py-2 text-sm">Review Proposals{pendingProposals == null ? "" : ` (${pendingProposals.toLocaleString()})`}</Link><Link href="/data-quality/repairs" className="rounded border border-[#334158] px-4 py-2 text-sm">Approved Repairs</Link></div></div><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy || Boolean(runId)} onClick={start} className="rounded border border-[#334158] px-4 py-2 text-sm disabled:opacity-50">Start full audit</button><button disabled={busy || !runId} onClick={process} className="rounded border border-[#334158] px-4 py-2 text-sm disabled:opacity-50">Process next 250</button></div>{runId && <p className="mt-2 break-all text-xs muted">Active run: {runId}</p>}{message && <p className="mt-3 text-sm text-amber-300">{message}</p>}</div>;
}
