import{cleanText,compactMetadata,normalizeAbsoluteNumber,normalizeCik,normalizeExchange,normalizeSecurityType,normalizeWebsite}from"../normalize";import{ProviderHttpError,ProviderQuotaError,fetchWithRetry,wait}from"../retry";import{metadataConfig}from"../config";import type{NormalizedExchange,ProviderReadiness,ProviderRequestOptions,ProviderResult,TickerMetadata,TickerMetadataProvider}from"../types";
type Overview=Record<string,string|undefined>;
export class AlphaVantageMetadataProvider implements TickerMetadataProvider{
 readonly name="alpha_vantage";readonly supportedFields=["company_name","exchange","primary_exchange","sector","industry","market_cap","shares_outstanding","country","website","security_type","cik","currency"]as const;
 constructor(private apiKey=process.env.ALPHA_VANTAGE_API_KEY,private fetcher:typeof fetch=fetch,private sleep:(ms:number)=>Promise<void>=wait){}
 readiness():ProviderReadiness{return{name:this.name,configured:Boolean(this.apiKey?.trim()),role:"market_data",message:this.apiKey?"Ready":"Set ALPHA_VANTAGE_API_KEY to enable on-demand company overview lookups.",rateLimit:`Application hard budget: ${metadataConfig.dailyBudget} external HTTP attempts/day, including retries. Provider-plan limits may be lower and are handled as deferrals.`,coverage:"Company Overview fields for provider-supported symbols, including company classification and capitalization where returned.",missingFields:["float","ISIN","CUSIP","reliable delisting status"]}}
 classifyExchange(value:unknown):NormalizedExchange|null{return normalizeExchange(value)}
 validateResponse(raw:unknown){const x=raw as Overview;return Boolean(x&&typeof x==="object"&&!Array.isArray(x)&&!x.Note&&!x.Information&&!x["Error Message"]&&(x.Symbol||x.Name))}
 normalizeSecurity(raw:unknown,symbol:string):TickerMetadata{void symbol;const x=raw as Overview,exchange=this.classifyExchange(x.Exchange);return compactMetadata({company_name:cleanText(x.Name),exchange,primary_exchange:exchange,sector:cleanText(x.Sector),industry:cleanText(x.Industry),market_cap:normalizeAbsoluteNumber(x.MarketCapitalization),shares_outstanding:normalizeAbsoluteNumber(x.SharesOutstanding),country:cleanText(x.Country,100),website:normalizeWebsite(x.OfficialSite),security_type:normalizeSecurityType(x.AssetType,x.Name),cik:normalizeCik(x.CIK),currency:cleanText(x.Currency,3)?.toUpperCase()??null,source_timestamp:new Date().toISOString(),confidence:.85})}
 async handleRateLimit(response:Response,attempt:number){await this.sleep(Math.min(30,Number(response.headers.get("retry-after"))||2**attempt)*1000)}
 async lookupTicker(rawSymbol:string,options?:ProviderRequestOptions):Promise<ProviderResult>{const symbol=rawSymbol.toUpperCase();if(!this.apiKey?.trim())return{symbol,provider:this.name,status:"failed",metadata:{},errorType:"unconfigured",errorMessage:"ALPHA_VANTAGE_API_KEY is not configured",retryable:false};try{const url=new URL("https://www.alphavantage.co/query");url.searchParams.set("function","OVERVIEW");url.searchParams.set("symbol",symbol);url.searchParams.set("apikey",this.apiKey);const response=await fetchWithRetry(url.toString(),{signal:options?.signal},{fetcher:this.fetcher,sleep:this.sleep,attempts:metadataConfig.maxRetries,timeoutMs:Math.min(metadataConfig.syncTimeoutMs,15_000),beforeAttempt:options?.beforeExternalCall}),payload=await response.json()as Overview;if(payload.Note||payload.Information)return{symbol,provider:this.name,status:"failed",metadata:{},errorType:"rate_limited",errorMessage:"Alpha Vantage rate limit or daily entitlement reached",retryable:true};if(payload["Error Message"]||Object.keys(payload).length===0)return{symbol,provider:this.name,status:"not_found",metadata:{},errorType:"not_found",errorMessage:"Alpha Vantage returned no supported company overview",retryable:false};if(!this.validateResponse(payload))return{symbol,provider:this.name,status:"failed",metadata:{},errorType:"malformed_response",errorMessage:"Alpha Vantage returned an unexpected Company Overview response",retryable:true};const metadata=this.normalizeSecurity(payload,symbol);return{symbol,provider:this.name,status:Object.keys(metadata).length>=5?"found":"partial",metadata}}catch(error){const rate=error instanceof ProviderHttpError&&error.status===429,quota=error instanceof ProviderQuotaError;return{symbol,provider:this.name,status:"failed",metadata:{},errorType:quota?"quota_exhausted":rate?"rate_limited":error instanceof DOMException&&error.name==="AbortError"?"timeout":"provider_request",errorMessage:quota?error.message:rate?"Alpha Vantage returned HTTP 429":error instanceof Error?error.message:String(error),retryable:!quota}}
 }
 async batchLookup(symbols:string[],options?:ProviderRequestOptions){const results:ProviderResult[]=[];for(const symbol of symbols)results.push(await this.lookupTicker(symbol,options));return results}
}
