import{cleanText,compactMetadata,normalizeAbsoluteNumber,normalizeExchange,normalizeIsin,normalizeSecurityType,normalizeWebsite}from"../normalize";import{ProviderQuotaError,fetchWithRetry,wait}from"../retry";import type{NormalizedExchange,ProviderReadiness,ProviderRequestOptions,ProviderResult,TickerMetadata,TickerMetadataProvider}from"../types";
type DirectoryRow={symbol?:string;description?:string;displaySymbol?:string;type?:string;mic?:string;currency?:string;isin?:string};type Profile={name?:string;country?:string;currency?:string;exchange?:string;finnhubIndustry?:string;marketCapitalization?:number;shareOutstanding?:number;weburl?:string;ticker?:string};
export class FinnhubMetadataProvider implements TickerMetadataProvider{
 readonly name="finnhub";private directoryCache:{expires:number;rows:Map<string,DirectoryRow>}|null=null;
 readonly supportedFields=["company_name","exchange","primary_exchange","sector","industry","country","website","market_cap","shares_outstanding","security_type","isin","currency"]as const;
 constructor(private token=process.env.FINNHUB_API_KEY,private fetcher:typeof fetch=fetch,private sleep:(ms:number)=>Promise<void>=wait){}
 readiness():ProviderReadiness{return{name:this.name,configured:Boolean(this.token?.trim()),role:"market_data",message:this.token?"Ready":"Set FINNHUB_API_KEY to enable the optional market-data supplement.",rateLimit:"Vendor-account limits apply; requests use bounded retries and a maximum of five concurrent profile calls.",coverage:"US symbol directory plus company profile fields where the subscribed vendor tier returns them.",missingFields:["float","CIK","ISIN","CUSIP"]}}
 classifyExchange(value:unknown):NormalizedExchange|null{return normalizeExchange(value)}
 validateResponse(raw:unknown){return Boolean(raw&&typeof raw==="object"&&!Array.isArray(raw))}
 normalizeSecurity(raw:unknown,symbol:string):TickerMetadata{void symbol;const x=raw as{directory?:DirectoryRow;profile?:Profile},d=x.directory??{},p=x.profile??{},exchange=this.classifyExchange(p.exchange??d.mic);return compactMetadata({company_name:cleanText(p.name??d.description),exchange,primary_exchange:exchange,sector:cleanText(p.finnhubIndustry),industry:cleanText(p.finnhubIndustry),country:cleanText(p.country,100),website:normalizeWebsite(p.weburl),market_cap:normalizeAbsoluteNumber(p.marketCapitalization,1e6),shares_outstanding:normalizeAbsoluteNumber(p.shareOutstanding,1e6),security_type:normalizeSecurityType(d.type,p.name??d.description),isin:normalizeIsin(d.isin),currency:cleanText(p.currency??d.currency,3)?.toUpperCase()??null,source_timestamp:new Date().toISOString(),confidence:.8})}
 async handleRateLimit(response:Response,attempt:number){await this.sleep(Math.min(30,Number(response.headers.get("retry-after"))||2**attempt)*1000)}
 private url(path:string,params:Record<string,string>={}){const search=new URLSearchParams({...params,token:this.token??""});return`https://finnhub.io/api/v1/${path}?${search}`}
 private async directory(options?:ProviderRequestOptions){if(this.directoryCache&&this.directoryCache.expires>Date.now())return this.directoryCache.rows;if(!this.token?.trim())throw new Error("FINNHUB_API_KEY is not configured");const response=await fetchWithRetry(this.url("stock/symbol",{exchange:"US"}),{signal:options?.signal},{fetcher:this.fetcher,sleep:this.sleep,beforeAttempt:options?.beforeExternalCall}),payload=await response.json();if(!Array.isArray(payload))throw new Error("Finnhub symbol directory response was not an array");const rows=new Map<string,DirectoryRow>();for(const row of payload){const symbol=String(row.symbol??row.displaySymbol??"").toUpperCase();if(symbol)rows.set(symbol,row)}this.directoryCache={expires:Date.now()+6*60*60*1000,rows};return rows}
 private async profile(symbol:string,options?:ProviderRequestOptions):Promise<Profile>{const response=await fetchWithRetry(this.url("stock/profile2",{symbol}),{signal:options?.signal},{fetcher:this.fetcher,sleep:this.sleep,beforeAttempt:options?.beforeExternalCall});return await response.json()as Profile}
 async lookupTicker(symbol:string,options?:ProviderRequestOptions){return(await this.batchLookup([symbol],options))[0]}
 async batchLookup(symbols:string[],options?:ProviderRequestOptions):Promise<ProviderResult[]>{let directory:Map<string,DirectoryRow>;try{directory=await this.directory(options)}catch(error){const quota=error instanceof ProviderQuotaError;return symbols.map(symbol=>({symbol:symbol.toUpperCase(),provider:this.name,status:"failed",metadata:{},errorType:quota?"quota_exhausted":"provider_request",errorMessage:error instanceof Error?error.message:String(error),retryable:!quota}))}const results:ProviderResult[]=[];for(let offset=0;offset<symbols.length;offset+=5){const slice=symbols.slice(offset,offset+5);results.push(...await Promise.all(slice.map(async(raw):Promise<ProviderResult>=>{const symbol=raw.toUpperCase(),directoryRow=directory.get(symbol);if(!directoryRow)return{symbol,provider:this.name,status:"not_found",metadata:{}};try{const profile=await this.profile(symbol,options),metadata=this.normalizeSecurity({directory:directoryRow,profile},symbol);return{symbol,provider:this.name,status:Object.keys(metadata).length>3?"found":"partial",metadata}}catch(error){const quota=error instanceof ProviderQuotaError;return{symbol,provider:this.name,status:"failed",metadata:{},errorType:quota?"quota_exhausted":"provider_request",errorMessage:error instanceof Error?error.message:String(error),retryable:!quota}}})))}return results}
}
