import{cleanText,compactMetadata,normalizeCik,normalizeExchange}from"../normalize";import{ProviderQuotaError,fetchWithRetry,wait}from"../retry";import type{NormalizedExchange,ProviderReadiness,ProviderRequestOptions,ProviderResult,TickerMetadata,TickerMetadataProvider}from"../types";
type SecPayload={fields?:unknown;data?:unknown};
export class SecCompanyTickersProvider implements TickerMetadataProvider{
 readonly name="sec_company_tickers";private cache:{expires:number;bySymbol:Map<string,unknown[]>}|null=null;
 readonly supportedFields=["company_name","exchange","primary_exchange","cik"]as const;
 constructor(private userAgent=process.env.SEC_USER_AGENT,private fetcher:typeof fetch=fetch,private sleep:(ms:number)=>Promise<void>=wait){}
 readiness():ProviderReadiness{return{name:this.name,configured:Boolean(this.userAgent?.trim()),role:"reference",message:this.userAgent?"Ready":"Set SEC_USER_AGENT with an application name and contact address.",rateLimit:"SEC asks automated clients to stay at or below 10 requests/second; this provider uses one bulk reference request per cache window.",coverage:"SEC-listed company name, CIK, and exchange reference fields for supported US issuers.",missingFields:["sector","industry","market cap","float","shares outstanding","company website","security type"]}}
 classifyExchange(value:unknown):NormalizedExchange|null{return normalizeExchange(value)}
 validateResponse(raw:unknown){const x=raw as SecPayload;return Boolean(x&&Array.isArray(x.fields)&&Array.isArray(x.data))}
 normalizeSecurity(raw:unknown,symbol:string):TickerMetadata{void symbol;const row=Array.isArray(raw)?raw:[],company_name=cleanText(row[1]),exchange=this.classifyExchange(row[3]);return compactMetadata({company_name,exchange,primary_exchange:exchange,cik:normalizeCik(row[0]),source_timestamp:new Date().toISOString(),confidence:.98})}
 async handleRateLimit(response:Response,attempt:number){const seconds=Math.min(30,Number(response.headers.get("retry-after"))||2**attempt);await this.sleep(seconds*1000)}
 private async directory(options?:ProviderRequestOptions){if(this.cache&&this.cache.expires>Date.now())return this.cache.bySymbol;if(!this.userAgent?.trim())throw new Error("SEC_USER_AGENT is not configured");const response=await fetchWithRetry("https://www.sec.gov/files/company_tickers_exchange.json",{headers:{"User-Agent":this.userAgent,"Accept-Encoding":"gzip, deflate","Host":"www.sec.gov"},signal:options?.signal},{fetcher:this.fetcher,sleep:this.sleep,beforeAttempt:options?.beforeExternalCall}),payload=await response.json();if(!this.validateResponse(payload))throw new Error("SEC company ticker response did not match the documented tabular shape");const bySymbol=new Map<string,unknown[]>();for(const row of(payload as SecPayload).data as unknown[][]){const ticker=String(row?.[2]??"").trim().toUpperCase();if(ticker)bySymbol.set(ticker,row)}this.cache={expires:Date.now()+6*60*60*1000,bySymbol};return bySymbol}
 async lookupTicker(symbol:string,options?:ProviderRequestOptions){return(await this.batchLookup([symbol],options))[0]}
 async batchLookup(symbols:string[],options?:ProviderRequestOptions):Promise<ProviderResult[]>{try{const directory=await this.directory(options);return symbols.map(raw=>{const symbol=raw.toUpperCase(),row=directory.get(symbol);return row?{symbol,provider:this.name,status:"partial",metadata:this.normalizeSecurity(row,symbol)}:{symbol,provider:this.name,status:"not_found",metadata:{}}})}catch(error){const quota=error instanceof ProviderQuotaError;return symbols.map(symbol=>({symbol:symbol.toUpperCase(),provider:this.name,status:"failed",metadata:{},errorType:quota?"quota_exhausted":"provider_request",errorMessage:error instanceof Error?error.message:String(error),retryable:!quota}))}}
}
