import{NextResponse}from"next/server";import{createAdminClient}from"@/lib/supabase/admin";import{processSocialResearchQueue}from"@/lib/social/research-pipeline";import{redditConfiguration}from"@/lib/social/config";
export const runtime="nodejs";export const maxDuration=60;
export async function POST(request:Request){const db:any=createAdminClient();if(!db)return NextResponse.json({message:"Dedicated Supabase service credentials are not configured."},{status:503});let body:any;try{body=await request.json()}catch{return NextResponse.json({message:"A JSON body is required."},{status:400})}const action=String(body.action??"");try{
 if(action==="process")return NextResponse.json(await processSocialResearchQueue(db,{queueId:body.queueId?String(body.queueId):undefined,limit:Math.max(1,Math.min(Number(body.limit)||1,5))}));
 if(action==="retry"){const r=await db.rpc("retry_failed_social_research",{p_limit:Math.max(1,Math.min(Number(body.limit)||10,50))});if(r.error)throw r.error;return NextResponse.json({retried:r.data})}
 if(action==="queue_selection"){const provider=redditConfiguration();if(!provider.ready)return NextResponse.json({message:provider.message,queued:0,providerCalls:0,status:"approval_blocked"},{status:423});let selection=String(body.selection??"");if(selection==="ticker_ids")selection="selected_tickers";const allowed=new Set(["selected_tickers","selected_mover","watchlist","recent_movers","top_frequent"]);if(!allowed.has(selection))return NextResponse.json({message:"Unsupported selective scope."},{status:400});let tickerIds=Array.isArray(body.tickerIds)?body.tickerIds.map(String):null;if(selection==="selected_tickers"&&typeof body.symbols==="string"){const symbols=[...new Set(body.symbols.split(",").map((x:string)=>x.trim().toUpperCase()).filter((x:string)=>/^[A-Z][A-Z0-9.-]{0,14}$/.test(x)))].slice(0,50),found=await db.from("tickers").select("id,symbol").in("symbol",symbols);if(found.error)throw found.error;tickerIds=(found.data??[]).map((x:any)=>x.id);if(!tickerIds.length)return NextResponse.json({message:"No matching ticker symbols were found."},{status:404})}const r=await db.rpc("queue_social_research_selection",{p_selection:selection,p_ticker_ids:tickerIds,p_appearance_id:body.appearanceId??null,p_watchlist_id:body.watchlistId??null,p_limit:Math.max(1,Math.min(Number(body.limit)||10,50)),p_community:body.community??null});if(r.error)throw r.error;return NextResponse.json({...r.data,message:`Queued ${r.data?.queued??0} bounded social research request(s).`})}
 if(action==="tombstone_post"){const r=await db.rpc("tombstone_reddit_content",{p_post_id:String(body.postId),p_state:String(body.state),p_reason:String(body.reason??"Provider deletion compliance")});if(r.error)throw r.error;return NextResponse.json(r.data)}
 if(action==="tombstone_account"){const r=await db.rpc("tombstone_reddit_account",{p_account_id:String(body.accountId),p_reason:String(body.reason??"Provider deleted-author compliance")});if(r.error)throw r.error;return NextResponse.json(r.data)}
 return NextResponse.json({message:"Unsupported management action."},{status:400})}catch(error){return NextResponse.json({message:error instanceof Error?error.message:String(error)},{status:409})}}
